library(tm)
library(pdftools)
text=readLines("text_file.txt")
Corpus=Corpus(VectorSource(text))
Corpus=tm_map(Corpus, tolower)
Corpus=tm_map(Corpus, removePunctuation)
Corpus=tm_map(Corpus, removeNumbers)
Cleanset=tm_map(Corpus, removeWords, stopwords("english"))
Cleanset=tm_map(Cleanset, removeWords, c("",))
Cleanset=tm_map(Cleanset, gsub, pattern="rights", replacement="right")
Cleanset=tm_map(Cleanset, stripWhitespace)
#Cleanset=tm_map(Cleanset, PlainTextDocument)
dtm=TermDocumentMatrix(Cleanset, control = list(minWordLength=c(1,Inf)))
findFreqTerms(dtm, lowfreq = 20)
termfrequency=rowSums(as.matrix(dtm))
termfrequency=subset(termfrequency, termfrequency>=4)
library(ggplot2)
barplot(termfrequency, las=2, col = rainbow(20))

#WORDCLOUD
library(wordcloud)
m=as.matrix(dtm)
wordfreq=sort(rowSums(m), decreasing = TRUE)
set.seed(370)
graylevels=gray((wordfreq+10)/ (max(wordfreq)+10))
wordcloud(words = names(wordfreq), freq = wordfreq, min.freq = 3, random.order = T, colors = graylevels)
wordcloud(words = names(wordfreq), freq = wordfreq, min.freq = 3, random.order = T, colors = brewer.pal(6,"Dark2"))

wordcloud(Cleanset)